version: "3.1"

services:
  maria :
    image: docker.io/bitnami/mariadb:11.2
    container_name: mariadb
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB}
    networks:
      - backend
    restart: always

networks:
  backend:
